version: '3.8'

services:
  bitcoind:
    image: lnbook/bitcoind
    container_name: bitcoind
    restart: unless-stopped
    volumes:
      - /home/gratten/.bitcoin:/root/.bitcoin
    ports:
      - "18332:18332"  # RPC port
      - "18333:18333"  # P2P port
    entrypoint: bitcoind
    command:
      - "-testnet"
      - "-server=1"
      - "-txindex=1"
      - "-rpcbind=0.0.0.0"
      - "-rpcallowip=0.0.0.0/0"
      - "-rpcuser=${BTCUSER}"
      - "-rpcpassword=${PASSWORD}"

  postgres:
    image: postgres:16
    container_name: blockstamp_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: blockstamp
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT} 
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      postgres:
        condition: service_healthy
      bitcoind:
        condition: service_started
    restart: unless-stopped

volumes:
  bitcoind_data:
  postgres_data:
