version: '3.8'

services:
  bitcoind:
    image: lnbook/bitcoind:latest
    container_name: bitcoind
    ports:
      - "18443:18443"
      - "8332:8332"
    volumes:
      - bitcoind_data:/home/bitcoin/.bitcoin
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: blockstamp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: blockstamp
    ports:
      - "8000:8000"
    depends_on:
      - bitcoind
    restart: unless-stopped

volumes:
  bitcoind_data:
  postgres_data:
